#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan  2 21:55:57 2024

@author: andreadesogus
"""

class InvertEmanante:
    def __init__(self):
        traduzioni = {
        'agenzia_del_territorio': 'Agenzia del Territorio',
        'agenzia_delle_dogane': 'Agenzia delle Dogane',
        'agenzia_delle_dogane_e_dei_monopoli': 'Agenzia delle Dogane e dei Monopoli',
        'agenzia_delle_entrate': 'Agenzia delle Entrate',
        'agenzia_entrate': 'Agenzia Entrate',
        'agenzia_per_le_erogazioni_in_agricoltura': 'Agenzia per le Erogazioni in Agricoltura',
        'agenzia_per_litalia_digitale': "Agenzia per l'Italia Digitale",
        'aipa': 'AIPA',
        'aran': 'ARAN',
        'banca_ditalia': "Banca d'Italia",
        'cassa_depositi_e_prestiti': 'Cassa Depositi e Prestiti',
        'digitpa': 'DigitPA',
        'dipartimento_delle_finanze': 'Dipartimento delle Finanze',
        'dipartimento_politiche_fiscali': 'Dipartimento Politiche Fiscali',
        'inps': 'INPS',
        'min_agricoltura': "Ministero dell'Agricoltura",
        'min_ambiente_e_tutela_terr_e_mare': "Ministero dell'Ambiente e Tutela del Territorio e del Mare",
        'min_attività_produttive': 'Ministero delle Attività Produttive',
        'min_comm_estero': 'Ministero degli Affari Esteri',
        'min_difesa': 'Ministero della Difesa',
        'min_economia_e_finanze': "Ministero dell'Economia e Finanze",
        'min_finanze': 'Ministero delle Finanze',
        'min_funz_pubbl_inform_e_sicur': "Ministero della Funzione Pubblica, dell'Informazione e della Sicurezza",
        'min_giustizia': 'Ministero della Giustizia',
        'min_industria': "Ministero dell'Industria",
        'min_infrastrutture_e_trasporti': 'Ministero delle Infrastrutture e dei Trasporti',
        'min_interni': "Ministero dell'Interno",
        'min_lavori_pubblici': 'Ministero dei Lavori Pubblici',
        'min_lavoro': 'Ministero del Lavoro',
        'min_sanità': 'Ministero della Sanità',
        'min_tesoro': 'Ministero del Tesoro',
        'min_trasporti': 'Ministero dei Trasporti',
        'ministero_della_funzione_pubblica': 'Ministero della Funzione Pubblica',
        'ministero_sviluppo_economico': 'Ministero dello Sviluppo Economico',
        'monopoli': 'Monopoli',
        'motoriz_civile': 'Motorizzazione Civile',
        'presidenza_consiglio_dei_ministri': 'Presidenza del Consiglio dei Ministri',
        'pubblica_amministraz_e_innovazione': 'Pubblica Amministrazione e Innovazione',
        'rag_gen_stato': 'Ragioneria Generale dello Stato',
        'ufficio_italiano_cambi': 'Ufficio Italiano Cambi',
        'Abruzzo': 'Abruzzo',
    'Arbitro': 'Arbitro',
    'Avvocato_Gen_Corte_Giust_Europea': 'Avvocato Generale della Corte di Giustizia Europea',
    'CTC_Bologna': 'CTC Bologna',
    'CTC_Firenze': 'CTC Firenze',
    'CTC_Milano': 'CTC Milano',
    'CTC_Napoli': 'CTC Napoli',
    'CTC_Palermo': 'CTC Palermo',
    'Calabria': 'Calabria',
    'Campania': 'Campania',
    'Comitato_Consult_norme_antielusive': 'Comitato Consultivo sulle norme antielusive',
    'Comm_Trib_Centrale': 'Commissione Tributaria Centrale',
    'Comm_Trib_II_grado_di_Bolzano': 'Commissione Tributaria di secondo grado di Bolzano',
    'Comm_Trib_II_grado_di_Trento': 'Commissione Tributaria di secondo grado di Trento',
    'Comm_Trib_Prov_Agrigento': 'Commissione Tributaria Provinciale di Agrigento',
    'Comm_Trib_Prov_Alessandria': 'Commissione Tributaria Provinciale di Alessandria',
    'Comm_Trib_Prov_Ancona': 'Commissione Tributaria Provinciale di Ancona',
    'Comm_Trib_Prov_Aosta': 'Commissione Tributaria Provinciale di Aosta',
    'Comm_Trib_Prov_Aquila': 'Commissione Tributaria Provinciale dell\'Aquila',
    'Comm_Trib_Prov_Arezzo': 'Commissione Tributaria Provinciale di Arezzo',
    'Comm_Trib_Prov_Ascoli_Piceno': 'Commissione Tributaria Provinciale di Ascoli Piceno',
    'Comm_Trib_Prov_Asti': 'Commissione Tributaria Provinciale di Asti',
    'Comm_Trib_Prov_Avellino': 'Commissione Tributaria Provinciale di Avellino',
    'Comm_Trib_Prov_Bari': 'Commissione Tributaria Provinciale di Bari',
    'Comm_Trib_Prov_Belluno': 'Commissione Tributaria Provinciale di Belluno',
    'Comm_Trib_Prov_Benevento': 'Commissione Tributaria Provinciale di Benevento',
    'Comm_Trib_Prov_Bergamo': 'Commissione Tributaria Provinciale di Bergamo',
    'Comm_Trib_Prov_Biella': 'Commissione Tributaria Provinciale di Biella',
    'Comm_Trib_Prov_Bologna': 'Commissione Tributaria Provinciale di Bologna',
    'Comm_Trib_Prov_Brescia': 'Commissione Tributaria Provinciale di Brescia',
    'Comm_Trib_Prov_Brindisi': 'Commissione Tributaria Provinciale di Brindisi',
    'Comm_Trib_Prov_Cagliari': 'Commissione Tributaria Provinciale di Cagliari',
    'Comm_Trib_Prov_Caltanissetta': 'Commissione Tributaria Provinciale di Caltanissetta',
    'Comm_Trib_Prov_Campobasso': 'Commissione Tributaria Provinciale di Campobasso',
    'Comm_Trib_Prov_Caserta': 'Commissione Tributaria Provinciale di Caserta',
    'Comm_Trib_Prov_Catania': 'Commissione Tributaria Provinciale di Catania',
    'Comm_Trib_Prov_Catanzaro': 'Commissione Tributaria Provinciale di Catanzaro',
    'Comm_Trib_Prov_Chieti': 'Commissione Tributaria Provinciale di Chieti',
    'Comm_Trib_Prov_Como': 'Commissione Tributaria Provinciale di Como',
    'Comm_Trib_Prov_Cosenza': 'Commissione Tributaria Provinciale di Cosenza',
    'Comm_Trib_Prov_Cremona': 'Commissione Tributaria Provinciale di Cremona',
    'Comm_Trib_Prov_Crotone': 'Commissione Tributaria Provinciale di Crotone',
    'Comm_Trib_Prov_Cuneo': 'Commissione Tributaria Provinciale di Cuneo',
    'Comm_Trib_Prov_Enna': 'Commissione Tributaria Provinciale di Enna',
    'Comm_Trib_Prov_Ferrara': 'Commissione Tributaria Provinciale di Ferrara',
    'Comm_Trib_Prov_Firenze': 'Commissione Tributaria Provinciale di Firenze',
    'Comm_Trib_Prov_Foggia': 'Commissione Tributaria Provinciale di Foggia',
    'Comm_Trib_Prov_Forlì': 'Commissione Tributaria Provinciale di Forlì',
    'Comm_Trib_Prov_Frosinone': 'Commissione Tributaria Provinciale di Frosinone',
    'Comm_Trib_Prov_Genova': 'Commissione Tributaria Provinciale di Genova',
    'Comm_Trib_Prov_Gorizia': 'Commissione Tributaria Provinciale di Gorizia',
    'Comm_Trib_Prov_Grosseto': 'Commissione Tributaria Provinciale di Grosseto',
    'Comm_Trib_Prov_Imperia': 'Commissione Tributaria Provinciale di Imperia',
    'Comm_Trib_Prov_Isernia': 'Commissione Tributaria Provinciale di Isernia',
    'Comm_Trib_Prov_La_Spezia': 'Commissione Tributaria Provinciale di La Spezia',
    'Comm_Trib_Prov_Latina': 'Commissione Tributaria Provinciale di Latina',
    'Comm_Trib_Prov_Lecce': 'Commissione Tributaria Provinciale di Lecce',
    'Comm_Trib_Prov_Lecco': 'Commissione Tributaria Provinciale di Lecco',
    'Comm_Trib_Prov_Livorno': 'Commissione Tributaria Provinciale di Livorno',
    'Comm_Trib_Prov_Lodi': 'Commissione Tributaria Provinciale di Lodi',
    'Comm_Trib_Prov_Lucca': 'Commissione Tributaria Provinciale di Lucca',
    'Comm_Trib_Prov_Macerata': 'Commissione Tributaria Provinciale di Macerata',
    'Comm_Trib_Prov_Mantova': 'Commissione Tributaria Provinciale di Mantova',
    'Comm_Trib_Prov_Massa_Carrara': 'Commissione Tributaria Provinciale di Massa Carrara',
    'Comm_Trib_Prov_Matera': 'Commissione Tributaria Provinciale di Matera',
    'Comm_Trib_Prov_Messina': 'Commissione Tributaria Provinciale di Messina',
    'Comm_Trib_Prov_Milano': 'Commissione Tributaria Provinciale di Milano',
    'Comm_Trib_Prov_Modena': 'Commissione Tributaria Provinciale di Modena',
    'Comm_Trib_Prov_Napoli': 'Commissione Tributaria Provinciale di Napoli',
    'Comm_Trib_Prov_Novara': 'Commissione Tributaria Provinciale di Novara',
    'Comm_Trib_Prov_Nuoro': 'Commissione Tributaria Provinciale di Nuoro',
    'Comm_Trib_Prov_Oristano': 'Commissione Tributaria Provinciale di Oristano',
    'Comm_Trib_Prov_Padova': 'Commissione Tributaria Provinciale di Padova',
    'Comm_Trib_Prov_Palermo': 'Commissione Tributaria Provinciale di Palermo',
    'Comm_Trib_Prov_Parma': 'Commissione Tributaria Provinciale di Parma',
    'Comm_Trib_Prov_Pavia': 'Commissione Tributaria Provinciale di Pavia',
    'Comm_Trib_Prov_Perugia': 'Commissione Tributaria Provinciale di Perugia',
    'Comm_Trib_Prov_Pesaro': 'Commissione Tributaria Provinciale di Pesaro',
    'Comm_Trib_Prov_Pescara': 'Commissione Tributaria Provinciale di Pescara',
    'Comm_Trib_Prov_Piacenza': 'Commissione Tributaria Provinciale di Piacenza',
    'Comm_Trib_Prov_Pisa': 'Commissione Tributaria Provinciale di Pisa',
    'Comm_Trib_Prov_Pistoia': 'Commissione Tributaria Provinciale di Pistoia',
    'Comm_Trib_Prov_Pordenone': 'Commissione Tributaria Provinciale di Pordenone',
    'Comm_Trib_Prov_Potenza': 'Commissione Tributaria Provinciale di Potenza',
    'Comm_Trib_Prov_Prato': 'Commissione Tributaria Provinciale di Prato',
    'Comm_Trib_Prov_Ragusa': 'Commissione Tributaria Provinciale di Ragusa',
    'Comm_Trib_Prov_Ravenna': 'Commissione Tributaria Provinciale di Ravenna',
    'Comm_Trib_Prov_Reggio_Calabria': 'Commissione Tributaria Provinciale di Reggio Calabria',
    'Comm_Trib_Prov_Reggio_Emilia': 'Commissione Tributaria Provinciale di Reggio Emilia',
    'Comm_Trib_Prov_Rieti': 'Commissione Tributaria Provinciale di Rieti',
    'Comm_Trib_Prov_Rimini': 'Commissione Tributaria Provinciale di Rimini',
    'Comm_Trib_Prov_Roma': 'Commissione Tributaria Provinciale di Roma',
    'Comm_Trib_Prov_Rovigo': 'Commissione Tributaria Provinciale di Rovigo',
    'Comm_Trib_Prov_Salerno': 'Commissione Tributaria Provinciale di Salerno',
    'Comm_Trib_Prov_Sassari': 'Commissione Tributaria Provinciale di Sassari',
    'Comm_Trib_Prov_Savona': 'Commissione Tributaria Provinciale di Savona',
    'Comm_Trib_Prov_Siena': 'Commissione Tributaria Provinciale di Siena',
    'Comm_Trib_Prov_Siracusa': 'Commissione Tributaria Provinciale di Siracusa',
    'Comm_Trib_Prov_Sondrio': 'Commissione Tributaria Provinciale di Sondrio',
    'Comm_Trib_Prov_Taranto': 'Commissione Tributaria Provinciale di Taranto',
    'Comm_Trib_Prov_Teramo': 'Commissione Tributaria Provinciale di Teramo',
    'Comm_Trib_Prov_Terni': 'Commissione Tributaria Provinciale di Terni',
    'Comm_Trib_Prov_Torino': 'Commissione Tributaria Provinciale di Torino',
    'Comm_Trib_Prov_Trapani': 'Commissione Tributaria Provinciale di Trapani',
    'Comm_Trib_Prov_Treviso': 'Commissione Tributaria Provinciale di Treviso',
    'Comm_Trib_Prov_Trieste': 'Commissione Tributaria Provinciale di Trieste',
    'Comm_Trib_Prov_Udine': 'Commissione Tributaria Provinciale di Udine',
    'Comm_Trib_Prov_Varese': 'Commissione Tributaria Provinciale di Varese',
    'Comm_Trib_Prov_Venezia': 'Commissione Tributaria Provinciale di Venezia',
    'Comm_Trib_Prov_Verbania': 'Commissione Tributaria Provinciale di Verbania',
    'Comm_Trib_Prov_Vercelli': 'Commissione Tributaria Provinciale di Vercelli',
    'Comm_Trib_Prov_Verona': 'Commissione Tributaria Provinciale di Verona',
    'Comm_Trib_Prov_Vibo_Valentia': 'Commissione Tributaria Provinciale di Vibo Valentia',
    'Comm_Trib_Prov_Vicenza': 'Commissione Tributaria Provinciale di Vicenza',
    'Comm_Trib_Prov_Viterbo': 'Commissione Tributaria Provinciale di Viterbo',
    'Comm_Trib_Reg_Emilia_Romagna': 'Commissione Tributaria Regionale dell\'Emilia Romagna',
    'Comm_Trib_Reg_Friuli_Venezia_Giulia': 'Commissione Tributaria Regionale del Friuli Venezia Giulia',
    'Comm_Trib_Reg_Valle_dAosta': 'Commissione Tributaria Regionale della Valle d\'Aosta',
    'Comm_Trib_Reg_per_il_Lazio': 'Commissione Tributaria Regionale per il Lazio',
    'Comm_Trib_Reg_per_il_Molise': 'Commissione Tributaria Regionale per il Molise',
    'Comm_Trib_Reg_per_il_Piemonte': 'Commissione Tributaria Regionale per il Piemonte',
    'Comm_Trib_Reg_per_il_Veneto': 'Commissione Tributaria Regionale per il Veneto',
    'Comm_Trib_Reg_per_lAbruzzo': 'Commissione Tributaria Regionale per l\'Abruzzo',
    'Comm_Trib_Reg_per_lUmbria': 'Commissione Tributaria Regionale per l\'Umbria',
    'Comm_Trib_Reg_per_la_Basilicata': 'Commissione Tributaria Regionale per la Basilicata',
    'Comm_Trib_Reg_per_la_Calabria': 'Commissione Tributaria Regionale per la Calabria',
    'Comm_Trib_Reg_per_la_Campania': 'Commissione Tributaria Regionale per la Campania',
    'Comm_Trib_Reg_per_la_Liguria': 'Commissione Tributaria Regionale per la Liguria',
    'Comm_Trib_Reg_per_la_Lombardia': 'Commissione Tributaria Regionale per la Lombardia',
    'Comm_Trib_Reg_per_la_Puglia': 'Commissione Tributaria Regionale per la Puglia',
    'Comm_Trib_Reg_per_la_Sardegna': 'Commissione Tributaria Regionale per la Sardegna',
    'Comm_Trib_Reg_per_la_Sicilia': 'Commissione Tributaria Regionale per la Sicilia',
    'Comm_Trib_Reg_per_la_Toscana': 'Commissione Tributaria Regionale per la Toscana',
    'Comm_Trib_Reg_per_le_Marche': 'Commissione Tributaria Regionale per le Marche',
    'Comm_Trib__I_grado_di_Bolzano': 'Commissione Tributaria di Primo Grado di Bolzano',
    'Comm_Trib__I_grado_di_Trento': 'Commissione Tributaria di Primo Grado di Trento',
    'Comm_Trib_primo_grado_Ivrea': 'Commissione Tributaria di Primo Grado di Ivrea',
    'Cons_Giustizia_Ammva_Reg_Sicilia': 'Consiglio di Giustizia Amministrativa per la Regione Sicilia',
    'Consiglio_di_Stato': 'Consiglio di Stato',
    'Corte_Costituzionale': 'Corte Costituzionale',
    'Corte_dei_Conti': 'Corte dei Conti',
    'Corte_di_Appello': 'Corte di Appello',
    'Corte_di_Cassazione': 'Corte di Cassazione',
    'Corte_di_Giustizia_CEE': 'Corte di Giustizia delle Comunità Europee',
    'Corte_di_Giustizia_UE': 'Corte di Giustizia dell\'Unione Europea',
    'Corte_di_giustizia_tributaria_di_primo_grado_di_Caserta': 'Corte di Giustizia Tributaria di Primo Grado di Caserta',
    'Corte_di_giustizia_tributaria_di_primo_grado_di_Frosinone': 'Corte di Giustizia Tributaria di Primo Grado di Frosinone',
    'Corte_di_giustizia_tributaria_di_primo_grado_di_Genova': 'Corte di Giustizia Tributaria di Primo Grado di Genova',
    'Corte_di_giustizia_tributaria_di_primo_grado_di_Imperia': 'Corte di Giustizia Tributaria di Primo Grado di Imperia',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_LAquila': 'Corte di Giustizia Tributaria di Primo Grado de LAquila',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_La_Spezia': 'Corte di Giustizia Tributaria di Primo Grado di La Spezia',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_Matera': 'Corte di Giustizia Tributaria di Primo Grado di Matera',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_Milano': 'Corte di Giustizia Tributaria di Primo Grado di Milano',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_Napoli': 'Corte di Giustizia Tributaria di Primo Grado di Napoli',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_Palermo': 'Corte di Giustizia Tributaria di Primo Grado di Palermo',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_Parma': 'Corte di Giustizia Tributaria di Primo Grado di Parma',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_Pescara': 'Corte di Giustizia Tributaria di Primo Grado di Pescara',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_Piacenza': 'Corte di Giustizia Tributaria di Primo Grado di Piacenza',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_Pordenone': 'Corte di Giustizia Tributaria di Primo Grado di Pordenone',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_Reggio_Emilia': 'Corte di Giustizia Tributaria di Primo Grado di Reggio Emilia',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_Roma': 'Corte di Giustizia Tributaria di Primo Grado di Roma',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_Savona': 'Corte di Giustizia Tributaria di Primo Grado di Savona',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_Trieste': 'Corte di Giustizia Tributaria di Primo Grado di Trieste',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_Udine': 'Corte di Giustizia Tributaria di Primo Grado di Udine',
     'Corte_di_giustizia_tributaria_di_primo_grado_di_Venezia': 'Corte di Giustizia Tributaria di Primo Grado di Venezia',
     'Corte_di_giustizia_tributaria_di_secondo_grado_del_Friuli_Venezia_Giulia': 'Corte di Giustizia Tributaria di Secondo Grado del Friuli Venezia Giulia',
     'Corte_di_giustizia_tributaria_di_secondo_grado_del_Lazio': 'Corte di Giustizia Tributaria di Secondo Grado del Lazio',
     'Corte_di_giustizia_tributaria_di_secondo_grado_del_Piemonte': 'Corte di Giustizia Tributaria di Secondo Grado del Piemonte',
     'Corte_di_giustizia_tributaria_di_secondo_grado_del_Veneto': 'Corte di Giustizia Tributaria di Secondo Grado del Veneto',
     'Corte_di_giustizia_tributaria_di_secondo_grado_dellAbruzzo': 'Corte di Giustizia Tributaria di Secondo Grado dellAbruzzo',
     'Corte_di_giustizia_tributaria_di_secondo_grado_dellEmilia_Romagna': 'Corte di Giustizia Tributaria di Secondo Grado dellEmilia Romagna',
     'Corte_di_giustizia_tributaria_di_secondo_grado_dellUmbria': 'Corte di Giustizia Tributaria di Secondo Grado dellUmbria',
     'Corte_di_giustizia_tributaria_di_secondo_grado_della_Basilicata': 'Corte di Giustizia Tributaria di Secondo Grado della Basilicata',
     'Corte_di_giustizia_tributaria_di_secondo_grado_della_Calabria': 'Corte di Giustizia Tributaria di Secondo Grado della Calabria',
     'Corte_di_giustizia_tributaria_di_secondo_grado_della_Campania': 'Corte di Giustizia Tributaria di Secondo Grado della Campania',
     'Corte_di_giustizia_tributaria_di_secondo_grado_della_Liguria': 'Corte di Giustizia Tributaria di Secondo Grado della Liguria',
     'Corte_di_giustizia_tributaria_di_secondo_grado_della_Lombardia': 'Corte di Giustizia Tributaria di Secondo Grado della Lombardia',
     'Corte_di_giustizia_tributaria_di_secondo_grado_della_Puglia': 'Corte di Giustizia Tributaria di Secondo Grado della Puglia',
     'Corte_di_giustizia_tributaria_di_secondo_grado_della_Sardegna': 'Corte di Giustizia Tributaria di Secondo Grado della Sardegna',
     'Corte_di_giustizia_tributaria_di_secondo_grado_della_Sicilia': 'Corte di Giustizia Tributaria di Secondo Grado della Sicilia',
     'Corte_di_giustizia_tributaria_di_secondo_grado_della_Toscana': 'Corte di Giustizia Tributaria di Secondo Grado della Toscana',
     'Corte_di_giustizia_tributaria_di_secondo_grado_delle_Marche': 'Corte di Giustizia Tributaria di Secondo Grado delle Marche',
     'Corte_di_giustizia_tributaria_di_secondo_grado_di_Trento': 'Corte di Giustizia Tributaria di Secondo Grado di Trento',
     'Emilia_Romagna': 'Emilia Romagna',
     'Friuli_Venezia_Giulia': 'Friuli Venezia Giulia',
     'Giudice_di_Pace': 'Giudice di Pace',
     'Lazio': 'Lazio',
     'Liguria': 'Liguria',
     'Lombardia': 'Lombardia',
     'Marche': 'Marche',
     'Molise': 'Molise',
     'Piemonte': 'Piemonte',
     'Presidente_del_Consiglio_dei_Ministri': 'Presidente del Consiglio dei Ministri',
     'Presidenza_Consiglio_dei_Ministri': 'Presidenza Consiglio dei Ministri',
     'Provincia_Autonoma_Bolzano': 'Provincia Autonoma di Bolzano',
     'Provincia_Autonoma_Trento': 'Provincia Autonoma di Trento',
     'Sardegna': 'Sardegna',
     'SezioneCollegio_20': 'Sezione Collegio 20',
     'Sicilia': 'Sicilia',
     'Stato': 'Stato',
     'Toscana': 'Toscana',
     'Tr_Amm_Reg_Friuli_Venezia_Giulia': 'Tribunale Amministrativo Regionale del Friuli Venezia Giulia',
     'Trentino_Alto_Adige': 'Trentino Alto Adige',
     'Trib_Amm_Provincia_Aut_Bolzano': 'Tribunale Amministrativo Provincia Autonoma di Bolzano',
     'Trib_Amm_Provincia_Aut_Trento': 'Tribunale Amministrativo Provincia Autonoma di Trento',
     'Trib_Amm_Reg_Emilia_Romagna': 'Tribunale Amministrativo Regione Emilia Romagna',
     'Trib_Amm_Reg_Valle_dAosta': 'Tribunale Amministrativo Regione Valle dAosta',
     'Trib_Amm_Reg_per_il_Lazio': 'Tribunale Amministrativo Regione per il Lazio',
     'Trib_Amm_Reg_per_il_Molise': 'Tribunale Amministrativo Regione per il Molise',
     'Trib_Amm_Reg_per_il_Piemonte': 'Tribunale Amministrativo Regione per il Piemonte',
     'Trib_Amm_Reg_per_il_Puglia': 'Tribunale Amministrativo Regione per il Puglia',
     'Trib_Amm_Reg_per_il_Veneto': 'Tribunale Amministrativo Regione per il Veneto',
     'Trib_Amm_Reg_per_lAbruzzo': 'Tribunale Amministrativo Regione per lAbruzzo',
     'Trib_Amm_Reg_per_lUmbria': 'Tribunale Amministrativo Regione per lUmbria',
     'Trib_Amm_Reg_per_la_Basilicata': 'Tribunale Amministrativo Regione per la Basilicata',
     'Trib_Amm_Reg_per_la_Calabria': 'Tribunale Amministrativo Regione per la Calabria',
     'Trib_Amm_Reg_per_la_Campania': 'Tribunale Amministrativo Regione per la Campania',
     'Trib_Amm_Reg_per_la_Liguria': 'Tribunale Amministrativo Regione per la Liguria',
     'Trib_Amm_Reg_per_la_Lombardia': 'Tribunale Amministrativo Regione per la Lombardia',
     'Trib_Amm_Reg_per_la_Sardegna': 'Tribunale Amministrativo Regione per la Sardegna',
     'Trib_Amm_Reg_per_la_Sicilia': 'Tribunale Amministrativo Regione per la Sicilia',
     'Trib_Amm_Reg_per_la_Toscana': 'Tribunale Amministrativo Regione per la Toscana',
     'Trib_Amm_Reg_per_le_Marche': 'Tribunale Amministrativo Regione per le Marche',
     'Tribunale': 'Tribunale',
     'Tribunale_I_grado_Corte_Giust_CE': 'Tribunale di Primo Grado della Corte di Giustizia CE',
     'Umbria': 'Umbria',
     'Valle_dAosta': 'Valle dAosta',
     'Veneto': 'Veneto'
        }
        self.traduzioni: Dict[str,str] = traduzioni
    def key2value(self, k: str):
        return self.traduzioni[k]
    
    def value2key(self, k: str):
        traduzioni_invertite = {valore: chiave for chiave, valore in self.traduzioni.items()}
        return traduzioni_invertite[k]
    
    def emananti_list(self):
        return list(self.traduzioni.values())



